var l=prompt("enter the value of l");
l=parseInt(l);
var b=prompt("enter the value of b");
b=parseInt(b);
var h=prompt("enter the value of h");
h=parseInt(h);
var volume;
var volume=(l*b*h);
var surfacearea;
var surfacearea=(2*(l*b+b*h+l*h));
alert(surfacearea);